### ISSUE TITLE
Use unsigned integers instead of signed integers where appropriate

### ISSUE THREAD

**Issue by johannesvollmer** [kryptan/rect_packer#3]
Please correct me if I am wrong!

From what I can see, the packer uses signed integers in places where unsigned integers would be appropriate.

This would simplify checks like `if width <= 0 || height <= 0 { return None }`. The `Rect` struct uses signed integers, although a Rectangle with width or height smaller than 0 will not work anyways.

Also, as a user of the library, I was expecting unsigned coordinates, and I had to check this libraries source code to see if I have to check for negative values in my own code. Using unsigned integers would document the intent of the library.

**Comment by kryptan** [comment]
Unsigned integers are usually harder to work with. For example, with signed integers I can write `a - b > 5`, `a > b + 5`, `a - 5 > b`, `a - b - 5 > 0`, etc, and they all mean the same thing for reasonably small values  of `a` and `b`. In contrast, with unsigned integers you can only use `a > b + 5` as all other variants can easily overflow even with small integers, so you need to continuously think about such issues. In my experience, it is much easier to get overflow bugs with unsigned integers rather than with signed.

Also you can read [this comment](https://github.com/ericniebler/stl2/issues/182#issuecomment-287683189) for more arguments in favour of signed integers. Rust embraces unsigned integers in the standard library but I think it is a mistake (e.g. simple things like `i < vec.len() - 1` do not work).

Even if we decide to switch to unsigned integers, I think coordinates (x/y) should still be signed and only sizes (width/height) be unsigned but this will lead to a lot of casts.

**Comment by johannesvollmer** [comment]
Oh okay, how about adjusting the API such that there is a cast from unsigned to signed once in the beginning?
